### ISSUE TITLE
add analyser

### ISSUE THREAD

**Issue by BenjaminDecaillet** [BenjaminDecaillet/M05-mp-decaillet#19]
Add analyser:
- handle split test/train
- repeats the training/testing process
- compute and aggregates fig of merits (MAE)

Analyser creation should be done using factory pattern and returning the correct one based on arguments

**Comment by decaillet** [comment]
On second thought, I'm not convinced the factory brings a lot.

Currently implemented without factory/IoD, directly in class Evaluator. See PR #31
