### ISSUE TITLE
Enables packaging

### ISSUE THREAD

**Issue by BenjaminDecaillet** [BenjaminDecaillet/M05-mp-decaillet#45]
Enable packaging for the project -> name is decm05

**Comment by BenjaminDecaillet** [comment]
Check https://github.com/python-versioneer/python-versioneer to use versionning

**Comment by BenjaminDecaillet** [comment]
See warning message:
[main-ci-action / main-ci-action](https://github.com/master-ai-batch5/M05-mp-decaillet/actions/runs/4519977703/jobs/7960784595#step:3:8)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by decaillet** [comment]
#60
